worker_processes 1;

events {
    worker_connections 1024;
}

http {

   upstream dotnet_api {
    least_conn;

    server dockerwithngnix-dockerwithngnix-1:8080;
    server dockerwithngnix-dockerwithngnix-2:8080;
    server dockerwithngnix-dockerwithngnix-3:8080;
   }

    upstream adminer_service {
        server adminer:8080;
    }

    server {
        listen 80;

        # Root redirect
        location = / {
            return 302 /swagger/;
        }

        # Fix swagger without slash
        location = /swagger {
            return 301 /swagger/;
        }

        # Swagger
        location /swagger/ {
            proxy_pass http://dotnet_api;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # API
        location / {
            proxy_pass http://dotnet_api;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
             proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # CORS FIX
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
            add_header Access-Control-Allow-Headers "Authorization, Content-Type";

            # Handle preflight
            if ($request_method = OPTIONS) {
                return 200;
            }
        }

        # Adminer
        location /adminer/ {
            rewrite ^/adminer/(.*)$ /$1 break;

            proxy_pass http://adminer_service;

            proxy_set_header Host $host;
        }
    }
}