version: '3.8'

services:
  dockerwithngnix:
    image: ${DOCKER_REGISTRY-}dockerwithngnix
    build:
      context: ./DockerWithNgnix
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=nginxdb;User Id=sa;Password=Docker@123;Encrypt=False;TrustServerCertificate=True;
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - sqlserver

  sqlserver:
    build:
      context: ./DockerWithNgnix
      dockerfile: Dockerfile.mssql
    container_name: sqlserver2022
    environment:
      SA_PASSWORD: "Docker@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:   
    - C:/DockerWithNgnix/DockerWithNgnix/DockerWithNgnix/Init-db:/Init-db 
    restart: always


  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8082:8080"
    environment:
      ADMINER_DEFAULT_SERVER: sqlserver
    depends_on:
      - sqlserver
    restart: always

volumes:
  sqlserver_data:
